"""
Code execution sandbox for running agent-generated skills.

This module provides a secure environment for executing Python code
generated by the LLM agent. Skills are validated and executed in
a restricted Python environment with limited builtins.

Components:
- validation: Code validation (syntax, security, signature)
- manager: Sandbox execution management
- exceptions: Sandbox-related exceptions
"""

from .exceptions import (
    SandboxError,
    SkillExecutionError,
    SkillSecurityError,
    SkillSyntaxError,
    SkillTimeoutError,
    SkillValidationError,
)
from .manager import (
    ExecutionResult,
    SandboxConfig,
    SkillSandbox,
)
from .validation import (
    ValidationResult,
    extract_skill_metadata,
    validate_security,
    validate_signature,
    validate_skill,
    validate_syntax,
)

__all__ = [
    # Exceptions
    "SandboxError",
    "SkillExecutionError",
    "SkillSyntaxError",
    "SkillSecurityError",
    "SkillTimeoutError",
    "SkillValidationError",
    # Manager
    "SkillSandbox",
    "SandboxConfig",
    "ExecutionResult",
    # Validation
    "validate_skill",
    "validate_syntax",
    "validate_security",
    "validate_signature",
    "extract_skill_metadata",
    "ValidationResult",
]
