"""
Code execution sandbox for running agent-generated skills.

This module provides a secure environment for executing Python code
generated by the LLM agent. Skills are validated and executed in
isolated Docker containers with strict resource limits.

Components:
- validation: Code validation (syntax, security, signature)
- manager: Docker container management
- proxy: API proxy for sandbox communication
- exceptions: Sandbox-related exceptions
"""

from .exceptions import (
    SandboxCommunicationError,
    SandboxError,
    SandboxStartupError,
    SkillExecutionError,
    SkillSecurityError,
    SkillSyntaxError,
    SkillTimeoutError,
    SkillValidationError,
)
from .manager import (
    ExecutionResult,
    SandboxConfig,
    SkillSandbox,
)
from .proxy import (
    APIProxy,
    get_api_stub_code,
)
from .validation import (
    ValidationResult,
    extract_skill_metadata,
    validate_security,
    validate_signature,
    validate_skill,
    validate_syntax,
)

__all__ = [
    # Exceptions
    "SandboxError",
    "SandboxStartupError",
    "SandboxCommunicationError",
    "SkillExecutionError",
    "SkillSyntaxError",
    "SkillSecurityError",
    "SkillTimeoutError",
    "SkillValidationError",
    # Manager
    "SkillSandbox",
    "SandboxConfig",
    "ExecutionResult",
    # Proxy
    "APIProxy",
    "get_api_stub_code",
    # Validation
    "validate_skill",
    "validate_syntax",
    "validate_security",
    "validate_signature",
    "extract_skill_metadata",
    "ValidationResult",
]
